import { useEffect, useState } from 'react';
import { open } from '@tauri-apps/plugin-dialog';
import { invoke } from '@tauri-apps/api/core';
import { check } from '@tauri-apps/plugin-updater';
import { relaunch } from '@tauri-apps/plugin-process';
import { FolderOpen, Play, ShieldCheck, Languages, Files, AlertTriangle } from 'lucide-react';

type Action={sourcePath:string;destinationPath:string;category:string;reason:string;status:string};
type Plan={rootPath:string;actions:Action[];exclusions:string[];errors:string[]};
const ko={title:'FileMoa',subtitle:'안전하게 정리하고, 언제든 되돌리세요',choose:'폴더 선택',scan:'정리 미리보기',run:'정리 실행',sub:'하위 폴더 포함',empty:'정리할 폴더를 선택하세요',preview:'정리 예정',excluded:'보호 또는 제외됨',safety:'미리보기 없이는 어떤 파일도 이동하지 않습니다.',update:'업데이트 확인'};
const en={title:'FileMoa',subtitle:'Organize safely. Undo anytime.',choose:'Choose folder',scan:'Preview organization',run:'Apply organization',sub:'Include subfolders',empty:'Choose a folder to organize',preview:'Planned changes',excluded:'Protected or excluded',safety:'No file moves until you approve the preview.',update:'Check updates'};

export default function App(){
 const [english,setEnglish]=useState(false),[path,setPath]=useState(''),[sub,setSub]=useState(false),[plan,setPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const t=english?en:ko;
 async function choose(){const selected=await open({directory:true,multiple:false,title:t.choose});if(typeof selected==='string'){setPath(selected);setPlan(null);}}
 async function preview(){if(!path)return;setBusy(true);setNotice('');try{setPlan(await invoke<Plan>('plan_organization',{request:{rootPath:path,includeSubfolders:sub}}));}catch(e){setNotice(String(e));}finally{setBusy(false)}}
 async function execute(){if(!plan||!confirm(english?'Move the previewed files?':'미리 본 파일을 이동할까요?'))return;setBusy(true);try{const done=await invoke<Plan>('execute_organization',{plan});setPlan(done);setNotice(english?'Organization finished.':'정리가 완료되었습니다.');}catch(e){setNotice(String(e));}finally{setBusy(false)}}
 async function update(manual=true){setBusy(true);setNotice('');try{const available=await check();if(!available){if(manual)setNotice(english?'You already have the latest version.':'최신 버전을 사용하고 있습니다.');return;}const message=english?`Version ${available.version} is available. Download, install, and restart now?`:`새 버전 ${available.version}이 있습니다. 다운로드·설치 후 다시 시작할까요?`;if(confirm(message)){await available.downloadAndInstall();await relaunch();}}catch(e){if(manual)setNotice(english?`Update check failed: ${String(e)}`:`업데이트 확인에 실패했습니다: ${String(e)}`);}finally{setBusy(false)}}
 useEffect(()=>{void update(false);},[]);
 return <main><header><div className="brand"><Files size={30}/><div><h1>{t.title}</h1><p>{t.subtitle}</p></div></div><div className="header-actions"><button className="ghost" disabled={busy} onClick={()=>void update(true)}>{t.update}</button><button className="ghost" onClick={()=>setEnglish(!english)}><Languages size={18}/>{english?'한국어':'English'}</button></div></header><section className="hero"><ShieldCheck size={40}/><div><b>{t.safety}</b><span>Safe Mode · Local only · No deletion</span></div></section><section className="controls"><button className="primary" onClick={choose}><FolderOpen size={19}/>{t.choose}</button><code>{path||t.empty}</code><label><input type="checkbox" checked={sub} onChange={e=>setSub(e.target.checked)}/>{t.sub}</label><button className="secondary" disabled={!path||busy} onClick={preview}><Play size={18}/>{t.scan}</button></section>{notice&&<p className="notice"><AlertTriangle size={18}/>{notice}</p>}{plan&&<section className="results"><div className="result-head"><div><h2>{t.preview}</h2><p>{plan.actions.length} files · {plan.exclusions.length} exclusions</p></div><button className="primary" disabled={busy||plan.actions.every(a=>a.status==='executed')} onClick={execute}>{t.run}</button></div><div className="table"><div className="row heading"><span>Category</span><span>Source</span><span>Destination</span></div>{plan.actions.map((a,i)=><div className="row" key={i}><b>{a.category}</b><span title={a.sourcePath}>{a.sourcePath}</span><span title={a.destinationPath}>{a.destinationPath}</span></div>)}</div>{plan.exclusions.length>0&&<details><summary>{t.excluded} ({plan.exclusions.length})</summary>{plan.exclusions.map((x,i)=><p key={i}>{x}</p>)}</details>}</section>}</main>}
