import { useEffect, useMemo, useState } from 'react';
import { open } from '@tauri-apps/plugin-dialog';
import { invoke } from '@tauri-apps/api/core';
import { check } from '@tauri-apps/plugin-updater';
import { relaunch } from '@tauri-apps/plugin-process';
import { FolderOpen, Play, Settings, Tags, Copy, History, Undo2, Files, Search, FolderTree, ChevronDown } from 'lucide-react';
import './styles.css';

type Category={name:string;extensions:string[];enabled:boolean};
type Action={sourcePath:string;destinationPath:string;category:string;reason:string;status:string};
type Plan={rootPath:string;actions:Action[];exclusions:string[];errors:string[]};
type Duplicate={hash:string;sizeBytes:number;filePaths:string[];reclaimableBytes:number};
type Tab='organize'|'manage'|'safety';
const labels={ko:{organize:'정리',manage:'관리',safety:'안전',settings:'설정',folder:'폴더 선택',preview:'정리 미리보기',execute:'파일 이동',category:'사용자 카테고리',duplicates:'중복 파일 탐색',undo:'마지막 정리 되돌리기',history:'정리 기록',sub:'하위 폴더 포함',empty:'정리할 폴더를 선택하세요',nothing:'표시할 항목이 없습니다.',update:'업데이트 확인',language:'English',catTitle:'사용자 정의 카테고리',catHint:'이름과 확장자를 입력하세요. 예: 영수증 / pdf,xlsx',add:'카테고리 추가',scan:'중복 탐색 실행',plan:'정리 예정'},en:{organize:'Organize',manage:'Manage',safety:'Safety',settings:'Settings',folder:'Choose folder',preview:'Preview plan',execute:'Move files',category:'Custom categories',duplicates:'Find duplicates',undo:'Undo last run',history:'Run history',sub:'Include subfolders',empty:'Choose a folder to organize',nothing:'Nothing to show yet.',update:'Check updates',language:'한국어',catTitle:'Custom categories',catHint:'Enter a name and extensions. Example: Receipts / pdf,xlsx',add:'Add category',scan:'Scan duplicates',plan:'Planned changes'}};

export default function App(){
 const [lang,setLang]=useState<'ko'|'en'>(()=>(localStorage.getItem('filemoa-language') as 'ko'|'en')||'ko'),[tab,setTab]=useState<Tab>('organize'),[panel,setPanel]=useState('plan'),[path,setPath]=useState(''),[sub,setSub]=useState(false),[plan,setPlan]=useState<Plan|null>(null),[runs,setRuns]=useState<Plan[]>(()=>JSON.parse(localStorage.getItem('filemoa-runs')||'[]')),[cats,setCats]=useState<Category[]>(()=>JSON.parse(localStorage.getItem('filemoa-categories')||'[]')),[duplicates,setDuplicates]=useState<Duplicate[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[settings,setSettings]=useState(false),[name,setName]=useState(''),[exts,setExts]=useState('');const t=labels[lang];
 const total=useMemo(()=>plan?.actions.length??0,[plan]);
 async function choose(){const selected=await open({directory:true,multiple:false,title:t.folder});if(typeof selected==='string'){setPath(selected);setPlan(null);setPanel('plan')}}
 async function makePlan(){if(!path)return;setBusy(true);try{const p=await invoke<Plan>('plan_organization',{request:{rootPath:path,includeSubfolders:sub,customCategories:cats}});setPlan(p);setPanel('plan');setNotice('');}catch(e){setNotice(String(e));}finally{setBusy(false)}}
 async function execute(){if(!plan||!confirm(lang==='ko'?`${total}개 파일을 이동할까요?`:`Move ${total} files?`))return;setBusy(true);try{const done=await invoke<Plan>('execute_organization',{plan});setPlan(done);setRuns([done,...runs]);setPanel('history');setNotice(lang==='ko'?'정리가 완료되었습니다.':'Organization completed.');}catch(e){setNotice(String(e));}finally{setBusy(false)}}
 async function undo(){const run=runs[0];if(!run)return;setBusy(true);try{const done=await invoke<Plan>('undo_organization',{plan:run});setRuns([done,...runs.slice(1)]);setPlan(done);setNotice(lang==='ko'?'마지막 정리를 되돌렸습니다.':'Last organization was undone.');}catch(e){setNotice(String(e));}finally{setBusy(false)}}
 async function scanDuplicates(){if(!path)return;setBusy(true);try{setDuplicates(await invoke<Duplicate[]>('find_duplicates',{rootPath:path,includeSubfolders:sub}));setPanel('duplicates');}catch(e){setNotice(String(e));}finally{setBusy(false)}}
 async function update(manual=true){setBusy(true);try{const available=await check();if(!available){if(manual)setNotice(lang==='ko'?'최신 버전을 사용하고 있습니다.':'You already have the latest version.');return;}if(confirm(lang==='ko'?`새 버전 ${available.version}을 설치하고 다시 시작할까요?`:`Install ${available.version} and restart?`)){await available.downloadAndInstall();await relaunch();}}catch(e){if(manual)setNotice(String(e));}finally{setBusy(false)}}
 useEffect(()=>{void update(false);},[]);
 useEffect(()=>{localStorage.setItem('filemoa-language',lang);localStorage.setItem('filemoa-categories',JSON.stringify(cats));localStorage.setItem('filemoa-runs',JSON.stringify(runs));},[lang,cats,runs]);
 function addCategory(){const extensions=exts.split(',').map(x=>x.trim().replace(/^\./,'')).filter(Boolean);if(!name.trim()||!extensions.length)return;setCats([...cats,{name:name.trim(),extensions,enabled:true}]);setName('');setExts('');}
 const ribbon: [string, typeof FolderOpen, () => void | Promise<void>][] = tab==='organize'?[['folder',FolderOpen,choose],['preview',Search,makePlan],['execute',Play,execute]]:tab==='manage'?[['category',Tags,()=>setPanel('categories')],['duplicates',Copy,scanDuplicates]]:[['undo',Undo2,undo],['history',History,()=>setPanel('history')]];
 return <main><header><div className="brand"><Files size={29}/><div><h1>FileMoa</h1><p>{lang==='ko'?'안전하게 정리하고, 언제든 되돌리세요':'Organize safely. Undo anytime.'}</p></div></div><button className="settings" onClick={()=>setSettings(!settings)}><Settings size={20}/></button>{settings&&<div className="settings-menu"><button onClick={()=>void update(true)}>{t.update}</button><button onClick={()=>setLang(lang==='ko'?'en':'ko')}>{t.language}</button></div>}</header><nav className="tabs">{(['organize','manage','safety']as Tab[]).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{t[x]}</button>)}</nav><section className="ribbon">{ribbon.map(([key,Icon,fn])=><button key={String(key)} onClick={()=>{void (fn as () => void)();}} disabled={busy||((key==='preview'||key==='execute'||key==='duplicates')&&!path)}><Icon size={22}/><span>{t[key as keyof typeof t]}</span></button>)}<label><input type="checkbox" checked={sub} onChange={e=>setSub(e.target.checked)}/>{t.sub}</label><code>{path||t.empty}</code></section>{notice&&<p className="notice">{notice}</p>}<section className="workspace">{panel==='plan'&&<><h2>{t.plan}</h2>{plan?<><p>{total} files · {plan.exclusions.length} exclusions</p><div className="table">{plan.actions.map((a,i)=><div className="row" key={i}><b>{a.category}</b><span>{a.sourcePath}</span><span>→ {a.destinationPath}</span></div>)}</div></>:<Empty text={t.nothing}/>}</>}{panel==='categories'&&<><h2>{t.catTitle}</h2><p>{t.catHint}</p><div className="form"><input value={name} onChange={e=>setName(e.target.value)} placeholder={lang==='ko'?'카테고리 이름':'Category name'}/><input value={exts} onChange={e=>setExts(e.target.value)} placeholder="pdf,xlsx"/><button onClick={addCategory}>{t.add}</button></div>{cats.map((c,i)=><div className="card" key={i}><b>{c.name}</b><span>.{c.extensions.join(', .')}</span><label><input type="checkbox" checked={c.enabled} onChange={()=>setCats(cats.map((x,n)=>n===i?{...x,enabled:!x.enabled}:x))}/>{c.enabled?'ON':'OFF'}</label></div>)}</>}{panel==='duplicates'&&<><h2>{t.duplicates}</h2>{duplicates.length?duplicates.map((g,i)=><div className="card" key={i}><b>{g.filePaths.length} files · {(g.reclaimableBytes/1024/1024).toFixed(1)} MB</b>{g.filePaths.map(p=><span key={p}>{p}</span>)}</div>):<Empty text={t.nothing}/>}</>}{panel==='history'&&<><h2>{t.history}</h2>{runs.length?runs.map((r,i)=><div className="card" key={i}><b>{r.actions.filter(a=>a.status==='executed').length} files moved</b><span>{r.rootPath}</span>{i===0&&<button onClick={()=>void undo()}>{t.undo}</button>}</div>):<Empty text={t.nothing}/>}</>}</section></main>}
function Empty({text}:{text:string}){return <div className="empty"><FolderTree size={36}/><p>{text}</p></div>}
